---------------------------------------------------------------------
-------------------------Language Table------------------------------
---------------------------------------------------------------------
SDC.Lang = {
    DefaultName = "Change_Me!",
    PumpkinSmash = "Pumpkin Smash",
    MyProfile = "My Profile",
    MyProfile2 = "Select this to edit your profile!",
    Leaderboard = "Leaderboard",
    Leaderboard2 = "Select this to see the current leaderboard!",
    Leaderboard3 = "Leaderboard Below",
    IssueGrabbingProfile = "Had Trouble Grabbing Profile! Please Try Again!",
    Name = "Display Name",
    Name2 = "Select to change Display Name!",
    Name3 = "New Display Name",
    Name4 = "Put your new desired Display Name In Here!",
    TCaught = "Times Caught",
    TCaught2 = "This is how many times you have been caught by PD!",
    PSmashed = "Pumpkins Smashed",
    PSmashed2 = "This is the amount of pumpkins you have smashed without being caught!",
    InvalidName = "Invalid Name Entered!",
    NameUsed = "Name Already Taken!",
    NameChanged = "Name Changed To",
    CurrentPos = "Current Position",
    CurrentPos2 = "This is your current position on the leaderboard!",
    Unranked = "Unranked",
    NoRanked = "No One Is Ranked",
    NoRanked2 = "No one in city is ranked on the leaderboard!",
    MissingJobForThis = "Invalid Job For This Command!",
    NoPlayerNearby = "No One Is Nearby For This Command!",
    IssueReset = "An Issue Occured When Trying To Reset!",
    PersonClean = "This Person Was Clean! Never Smashed A Pumpkin In Their Life!",
    ResetPlayer = "Reset Persons Pumpkin Smash Count!",
    SmashPumpkin = "Smash Pumpkin",
    CantSmashPumpkin = "Cant Smash Pumpkin! Someone Else Is Smashing Pumpkin!",
    CantSmashPumpkin2 = "Cant Smash Pumpkin With That Job!",
    CantSmashPumpkin3 = "Cant Smash Pumpkin! Display Name Needs Changed!",
    CantSmashPumpkin4 = "Cant Smash Pumpkin! Missing",
    SmashingPumpkin = "Smashing Pumpkin",
    FailedPumpkinSmash = "You Failed At Smashing Pumpkins!",
    PumpkinSmashed = "Pumpkin Smashed",
    PumpkinSmashed2 = "Someone just smashed a pumpkin at the marked location!",
    SmashedPumpkin = "Smashed Pumpkin!"
}